use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :community_tools, CommunityToolsWeb.Endpoint,
  url: [host: "localhost"],
  http: [port: 80],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [node: ["node_modules/brunch/bin/brunch", "watch", "--stdin",
                    cd: Path.expand("../assets", __DIR__)]]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :community_tools, CommunityToolsWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/community_tools_web/views/.*(ex)$},
      ~r{lib/community_tools_web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :community_tools, CommunityTools.Repo,
  adapter: Ecto.Adapters.Postgres,
  #username: "opencamps_dev",
  username: "opencamps",
  password: "camps0p3n",
  database: "ee_oc_dev",
  #database: "opencamps_test",
  #database: "opencamps_live",
  hostname: "localhost",
  #hostname: "opencamps.clsbkxx9al65.us-east-1.rds.amazonaws.com",
  pool_size: 10


#  username: System.get_env("DB_USER"),
#  password: System.get_env("DB_PASSWORD"),
#  database: System.get_env("DB_NAME"),
#  hostname: System.get_env("DB_HOST"),


config :community_tools, ecto_repos: [CommunityTools.Repo]

#import_config "dev.secret.exs"
